// <auto-generated />
namespace Dao.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class MakeDriverIdNullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MakeDriverIdNullable));
        
        string IMigrationMetadata.Id
        {
            get { return "202506251139067_MakeDriverIdNullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
